-- ============================================================
-- MedBook Platform -> doctor-dmn
-- Migration: V5__rename_enum_values_to_italian.sql
-- Descrizione: Aggiornamento dei valori enum a italiano.
--              GENDER: MALE/FEMALE -> MASCHILE/FEMMINILE
--              STATUS: ACTIVE/INACTIVE/SUSPENDED -> ATTIVO/DISATTIVO/SOSPESO
--                      aggiunto IN_FERIE al vincolo CHECK
--              SPECIALIZATION: valori inglesi -> valori italiani
--              DAY_OF_WEEK: giorni inglesi -> giorni italiani
-- Autore: djizalfra@gmail.com
-- Data: 2026-03-30
-- Versione: 1.0.0
-- ============================================================

-- ============================================================
-- TABELLA: DOCTORS
-- ============================================================

-- Step 1a: Aggiornamento dati
UPDATE DOCTORS SET GENDER = 'MASCHILE'  WHERE GENDER = 'MALE';
UPDATE DOCTORS SET GENDER = 'FEMMINILE' WHERE GENDER = 'FEMALE';
UPDATE DOCTORS SET STATUS = 'ATTIVO'    WHERE STATUS = 'ACTIVE';
UPDATE DOCTORS SET STATUS = 'DISATTIVO' WHERE STATUS = 'INACTIVE';
UPDATE DOCTORS SET STATUS = 'SOSPESO'   WHERE STATUS = 'SUSPENDED';

-- Step 1b: Aggiornamento vincoli CHECK
ALTER TABLE DOCTORS DROP CONSTRAINT chk_doctors_gender;
ALTER TABLE DOCTORS ADD CONSTRAINT chk_doctors_gender
    CHECK (GENDER IN ('MASCHILE', 'FEMMINILE'));

ALTER TABLE DOCTORS DROP CONSTRAINT chk_doctors_status;
ALTER TABLE DOCTORS ADD CONSTRAINT chk_doctors_status
    CHECK (STATUS IN ('ATTIVO', 'DISATTIVO', 'SOSPESO', 'IN_FERIE'));

-- Step 1c: Aggiornamento DEFAULT
ALTER TABLE DOCTORS ALTER COLUMN STATUS SET DEFAULT 'ATTIVO';

-- ============================================================
-- TABELLA: DOCTOR_SPECIALIZATIONS
-- ============================================================

-- Step 2a: Aggiornamento dati - specializzazioni
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'CARDIOLOGIA'        WHERE SPECIALIZATION = 'CARDIOLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'DERMATOLOGIA'       WHERE SPECIALIZATION = 'DERMATOLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'ENDOCRINOLOGIA'     WHERE SPECIALIZATION = 'ENDOCRINOLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'GASTROENTEROLOGIA'  WHERE SPECIALIZATION = 'GASTROENTEROLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'MEDICINA_GENERALE'  WHERE SPECIALIZATION = 'GENERAL_MEDICINE';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'GINECOLOGIA'        WHERE SPECIALIZATION = 'GYNECOLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'MEDICINA_INTERNA'   WHERE SPECIALIZATION = 'INTERNAL_MEDICINE';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'NEUROLOGIA'         WHERE SPECIALIZATION = 'NEUROLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'ONCOLOGIA'          WHERE SPECIALIZATION = 'ONCOLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'OFTALMOLOGIA'       WHERE SPECIALIZATION = 'OPHTHALMOLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'ORTOPEDIA'          WHERE SPECIALIZATION = 'ORTHOPEDICS';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'OTORINOLARINGOIATRIA' WHERE SPECIALIZATION = 'OTOLARYNGOLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'PEDIATRIA'          WHERE SPECIALIZATION = 'PEDIATRICS';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'PSICHIATRIA'        WHERE SPECIALIZATION = 'PSYCHIATRY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'PNEUMOLOGIA'        WHERE SPECIALIZATION = 'PULMONOLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'RADIOLOGIA'         WHERE SPECIALIZATION = 'RADIOLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'REUMATOLOGIA'       WHERE SPECIALIZATION = 'RHEUMATOLOGY';
UPDATE DOCTOR_SPECIALIZATIONS SET SPECIALIZATION = 'UROLOGIA'           WHERE SPECIALIZATION = 'UROLOGY';

-- Step 2b: Aggiornamento dati - status
UPDATE DOCTOR_SPECIALIZATIONS SET STATUS = 'ATTIVO'    WHERE STATUS = 'ACTIVE';
UPDATE DOCTOR_SPECIALIZATIONS SET STATUS = 'DISATTIVO' WHERE STATUS = 'INACTIVE';

-- Step 2c: Aggiornamento vincolo CHECK status
ALTER TABLE DOCTOR_SPECIALIZATIONS DROP CONSTRAINT chk_specializations_status;
ALTER TABLE DOCTOR_SPECIALIZATIONS ADD CONSTRAINT chk_specializations_status
    CHECK (STATUS IN ('ATTIVO', 'DISATTIVO'));

-- Step 2d: Aggiornamento DEFAULT
ALTER TABLE DOCTOR_SPECIALIZATIONS ALTER COLUMN STATUS SET DEFAULT 'ATTIVO';

-- ============================================================
-- TABELLA: DOCTOR_AVAILABILITIES
-- ============================================================

-- Step 3a: Aggiornamento dati - giorni della settimana
UPDATE DOCTOR_AVAILABILITIES SET DAY_OF_WEEK = 'LUNEDI'    WHERE DAY_OF_WEEK = 'MONDAY';
UPDATE DOCTOR_AVAILABILITIES SET DAY_OF_WEEK = 'MARTEDI'   WHERE DAY_OF_WEEK = 'TUESDAY';
UPDATE DOCTOR_AVAILABILITIES SET DAY_OF_WEEK = 'MERCOLEDI' WHERE DAY_OF_WEEK = 'WEDNESDAY';
UPDATE DOCTOR_AVAILABILITIES SET DAY_OF_WEEK = 'GIOVEDI'   WHERE DAY_OF_WEEK = 'THURSDAY';
UPDATE DOCTOR_AVAILABILITIES SET DAY_OF_WEEK = 'VENERDI'   WHERE DAY_OF_WEEK = 'FRIDAY';
UPDATE DOCTOR_AVAILABILITIES SET DAY_OF_WEEK = 'SABATO'    WHERE DAY_OF_WEEK = 'SATURDAY';
UPDATE DOCTOR_AVAILABILITIES SET DAY_OF_WEEK = 'DOMENICA'  WHERE DAY_OF_WEEK = 'SUNDAY';

-- Step 3b: Aggiornamento dati - status
UPDATE DOCTOR_AVAILABILITIES SET STATUS = 'ATTIVO'    WHERE STATUS = 'ACTIVE';
UPDATE DOCTOR_AVAILABILITIES SET STATUS = 'DISATTIVO' WHERE STATUS = 'INACTIVE';

-- Step 3c: Aggiornamento vincoli CHECK
ALTER TABLE DOCTOR_AVAILABILITIES DROP CONSTRAINT chk_availabilities_day_of_week;
ALTER TABLE DOCTOR_AVAILABILITIES ADD CONSTRAINT chk_availabilities_day_of_week
    CHECK (DAY_OF_WEEK IN ('LUNEDI', 'MARTEDI', 'MERCOLEDI', 'GIOVEDI', 'VENERDI', 'SABATO', 'DOMENICA'));

ALTER TABLE DOCTOR_AVAILABILITIES DROP CONSTRAINT chk_availabilities_status;
ALTER TABLE DOCTOR_AVAILABILITIES ADD CONSTRAINT chk_availabilities_status
    CHECK (STATUS IN ('ATTIVO', 'DISATTIVO'));

-- Step 3d: Aggiornamento DEFAULT
ALTER TABLE DOCTOR_AVAILABILITIES ALTER COLUMN STATUS SET DEFAULT 'ATTIVO';
