-- Aggiunge i campi consenso GDPR alla tabella PATIENTS.
-- consensoPrivacy è obbligatorio (true alla registrazione).
-- consensoCommerciale e consensoProfilazione sono facoltativi.
ALTER TABLE PATIENTS ADD COLUMN CONSENSO_PRIVACY       BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE PATIENTS ADD COLUMN CONSENSO_COMMERCIALE   BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE PATIENTS ADD COLUMN CONSENSO_PROFILAZIONE  BOOLEAN NOT NULL DEFAULT FALSE;
