name: Local
variables:
  - name: base_url_keycloak
    value: http://localhost:8082
  - name: keycloak_realm
    value: medbook
  - name: client_id
    value: medbook-client
  - secret: true
    name: client_secret
  - name: username
    value: mario.rossi
  - name: password
    value: Test1234!
  - secret: true
    name: access_token
  - name: base_url_eureka
    value: http://localhost:8070
  - name: base_url_config_server
    value: http://localhost:8071
  - name: base_url_gateway
    value: http://localhost:8080
  - name: base_url_bff
    value: http://localhost:8081
  - name: base_url_patient
    value: http://localhost:8090
  - name: base_url_doctor
    value: http://localhost:8091
  - name: base_url_clinic
    value: http://localhost:8092
  - name: base_url_appointment
    value: http://localhost:80793
  - name: base_url_notification
    value: http://localhost:8094
