spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak locale per sviluppo
          issuer-uri: http://localhost:8082/realms/medbook

# config per abilitare il livello logging DEBUG
logging:
  level:
    it.pegaso.projectwork.medbook: DEBUG
